name: odhani_design_sqt
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  intl: ^0.19.0
  provider: ^6.1.1
  geolocator: ^11.0.0
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  flutter_svg: ^2.0.10+1
  webview_flutter: ^4.7.0
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.3
  cached_network_image: ^3.3.1
  flutter_secure_storage: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/icons/
    - assets/images/logo/
    - assets/images/graphics/
#    - assets/images/dummy_img/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 200


